# Site settings
title: Baltazore's corner
email: k.shaplyko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I am a Ruby developer with interests to new technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: _baltazore
github_username:  Baltazore

# Build settings
markdown: kramdown

